# Generated by Django 3.0.2 on 2020-02-25 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_module', models.CharField(max_length=200)),
                ('module_options', models.CharField(max_length=200)),
                ('module_arguments', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='state_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_name', models.CharField(max_length=200)),
                ('list_of_tasks', models.ManyToManyField(to='playbooks_parser.Task')),
            ],
        ),
    ]
