# Generated by Django 3.0.2 on 2020-02-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks_parser', '0002_auto_20200225_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='playbook_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
