# Generated by Django 3.0.2 on 2020-03-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks_parser', '0003_playbook_playbook_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_version',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
