# Generated by Django 3.0.2 on 2020-05-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks_parser', '0005_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_states', models.ManyToManyField(to='playbooks_parser.State')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=200)),
                ('cve_url', models.URLField()),
                ('impact', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Play',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_version',
        ),
        migrations.AddField(
            model_name='package',
            name='set_of_vulnerabilities',
            field=models.ManyToManyField(to='playbooks_parser.Vulnerability'),
        ),
    ]
