# Generated by Django 3.0.2 on 2020-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks_parser', '0006_auto_20200530_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='playbook_execution',
            field=models.ManyToManyField(to='playbooks_parser.PlaybookExecution'),
        ),
    ]
