# Generated by Django 3.0.2 on 2020-06-01 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks_parser', '0008_remove_task_playbook_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookexecution',
            name='execution_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
